mediaDirs: 
    - data/Music
mediaExts:
    - .mp3
    - .m4a
excludePaths:
    - ExcludeThisArtistDir
excludeTitle: []
excludeArtist: []
excludeAlbumArtist: []
excludeAlbum: []
excludeGenre: []
sortBy: year
groupBy: none
getMp3Duration: false